version: 2

models:
  - name: silver_trips
    description: "Cleaned rides from Bronze; 1 row = 1 ride."
    columns:
      - name: ride_id
        tests: [not_null, unique]

  - name: silver_weather
    description: "Daily weather aggregation; 1 row = 1 date."
    columns:
      - name: date
        tests: [not_null, unique]

  - name: silver_holidays
    description: "US and NY holidays for each date; 1 rida = 1 kuupäev."
    columns:
      - name: date
        tests: [not_null, unique]

  - name: dim_time
    description: "Calendar dimension; PK = time_id."
    columns:
      - name: time_id
        tests: [not_null, unique]

  - name: dim_weather
    description: "Weather dimension; PK = weather_id."
    columns:
      - name: weather_id
        tests: [not_null, unique]

  - name: dim_station
    description: "Station dimension; PK = station_id."
    columns:
      - name: station_id
        tests: [not_null, unique]

  - name: fact_bike_ride
    description: "Fact bike ride (start_date_id, end_station_id, user_type, bike_type) with trip duration."
    columns:
      - name: start_date_id
        tests: [not_null]
      - name: end_station_id
        tests: [not_null]

