version: "3.9"

services:
  # --- Airflow metadata database (Postgres, for Airflow internal use) ---
  airflow-db:
    container_name: airflow-db
    image: postgres:16.4
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata_airflow:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      retries: 5
    restart: always

  # --- ClickHouse analytical database ---
  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server:24.3
    environment:
      CLICKHOUSE_DB: bronze
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: clickhouse
    ports:
      - "8123:8123"   # HTTP interface
      - "9000:9000"   # Native port for clickhouse-driver
    volumes:
      - ./clickhouse_data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8123/ping"]
      interval: 10s
      retries: 5
    restart: always

  # --- Airflow Webserver ---
  airflow-webserver:
    build: .
    image: custom-airflow:latest
    container_name: airflow-webserver
    command: webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__API__AUTH_BACKENDS: "airflow.api.auth.backend.basic_auth"
      # Connection to ClickHouse (available as 'clickhouse_default' inside Airflow)
      AIRFLOW_CONN_CLICKHOUSE_DEFAULT: clickhouse+http://default:@clickhouse:8123/bronze
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./data/bronze/citibike:/opt/airflow/data/bronze/citibike
      - ./data/bronze/weather:/opt/airflow/data/bronze/weather

    depends_on:
      - airflow-init
      - airflow-db
      - clickhouse
    restart: always

  # --- Airflow Scheduler ---
  airflow-scheduler:
    build: .
    image: custom-airflow:latest
    container_name: airflow-scheduler
    command: scheduler
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW_CONN_CLICKHOUSE_DEFAULT: clickhouse+http://default:@clickhouse:8123/bronze
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./data/bronze/citibike:/opt/airflow/data/bronze/citibike
      - ./data/bronze/weather:/opt/airflow/data/bronze/weather

    depends_on:
      - airflow-init
      - airflow-db
      - clickhouse
    restart: always

  # --- Airflow initialization & user setup ---
  airflow-init:
    build: .
    image: custom-airflow:latest
    container_name: airflow-init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db init
        airflow users create \
          --username admin \
          --password admin \
          --firstname Admin \
          --lastname User \
          --role Admin \
          --email admin@example.com
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
    depends_on:
      - airflow-db
      - clickhouse
    restart: "no"

volumes:
  pgdata_airflow:
  clickhouse_data:
